Az
bettykatya/octonion_lessons pull request #4
Opened 2020-09-03 12:52 UTC by andrzakharevich

2020-09-08 14:20 UTC, bettykatya requested changes

2020-09-08 19:38 UTC, andrzakharevich commented on azakharevich/octonion/AQA_lessons/Calc.py
> +def checker (x):
We should discuss this point

2020-09-08 19:49 UTC, andrzakharevich commented on azakharevich/octonion/AQA_lessons/Calc.py
> +    x += 1
It's player count. X or O have to add new point

2020-09-08 19:50 UTC, andrzakharevich commented on azakharevich/octonion/AQA_lessons/Calc.py
> +    for var in range(5):
Should discuss

2020-09-10 13:02 UTC, bettykatya requested changes

2020-09-10 13:02 UTC, bettykatya commented on azakharevich/octonion/AQA_lessons/Calc.py
> +                for j in range(len(matrix)):
len(matrix) is used a lot in code, why not create a variable with len(matrix) value?

2020-10-06 07:12 UTC, bettykatya requested changes

2020-10-06 07:12 UTC, bettykatya commented on azakharevich/octonion/AQA_lessons/Class/person.py
> +        self.sortedArray = []
doesn't need to be 'self'

2020-10-06 07:12 UTC, bettykatya commented on azakharevich/octonion/AQA_lessons/Class/person.py
> +        for i in range(len(self.equipArray)): #Помню, что если использовали 2 раза, то можно вынести в отдельный метод, но копипаст тут быстрее ;)
nope, it is not faster)

2020-10-06 07:12 UTC, bettykatya commented on azakharevich/octonion/AQA_lessons/Class/person.py
> +            self.minEquip = self.equipArray[0]
doesn't need to be 'self'

2020-10-06 07:12 UTC, bettykatya commented on azakharevich/octonion/AQA_lessons/Class/person.py
> +            self.minIndex = 0
doesn't need to be 'self'

2020-10-06 07:12 UTC, bettykatya commented on azakharevich/octonion/AQA_lessons/Class/person.py
> +                self.currEquip = self.equipArray[i]
doesn't need to be 'self'

2020-10-06 07:12 UTC, bettykatya commented on azakharevich/octonion/AQA_lessons/Class/person.py
> +        self.searchResult = []
doesn't need to be 'self'

2020-10-06 07:12 UTC, bettykatya commented on azakharevich/octonion/AQA_lessons/Class/person.py
> +        print(' After:')
i would move both prints (before and after) to separate method that is called from main

2020-10-06 07:14 UTC, bettykatya requested changes

2020-10-06 07:14 UTC, bettykatya commented on azakharevich/octonion/AQA_lessons/Class/person.py
> +        print('\n\rSearch equip from', self.min,'to', self.max, '$')
it would be better to return list and print it outside

2020-10-08 12:50 UTC, bettykatya requested changes

2020-10-08 12:50 UTC, bettykatya commented on azakharevich/octonion/AQA_lessons/Class/person.py
> +        self.max = max
please check all classes for unneeded use of 'self'

2020-10-08 12:50 UTC, bettykatya commented on azakharevich/octonion/AQA_lessons/Class/person.py
> +    def equipWeightList(self):
rename

2020-10-08 12:50 UTC, bettykatya commented on azakharevich/octonion/AQA_lessons/Class/person.py
> +    def fullEquipPrice(self):
rename

2020-10-14 06:34 UTC, bettykatya requested changes

2020-10-16 10:36 UTC, bettykatya approved these changes

2020-10-16 10:37 UTC, merged